name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install build and deployment tools
        run: pip install ghp-import
      
      - name: generate emoji LUT
        run: python update_emoji_lut.py
        
      - name: deploy site
        run: ghp-import site --no-jekyll --push --no-history
     
